// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbRKuwbtA92enAt0IQufxLndfK3J9c9U0',
    appId: '1:551688859884:web:1f6fb356768a968583b5c9',
    messagingSenderId: '551688859884',
    projectId: 'barathamtoday',
    authDomain: 'barathamtoday.firebaseapp.com',
    storageBucket: 'barathamtoday.appspot.com',
    measurementId: 'G-G03K4GX2QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC32v_0pHNpw6dsSStXyk-T0xTuRmIGaKE',
    appId: '1:551688859884:android:0e2f6665a37d622a83b5c9',
    messagingSenderId: '551688859884',
    projectId: 'barathamtoday',
    storageBucket: 'barathamtoday.appspot.com',
  );
}
